# Little Shop of Horrors foot theme
# https://codeberg.org/dnkl/foot

[colors-dark]
alpha=0.93
alpha-mode=all

background=15100e
foreground=ece6c2

cursor=15100e f3d6a8
selection-foreground=15100e
selection-background=87c700

regular0=2a201d
regular1=d44a3a
regular2=87c700
regular3=f3d6a8
regular4=9472b1
regular5=c44a64
regular6=438a8a
regular7=ece6c2

bright0=5a4a44
bright1=e36b58
bright2=a6e34e
bright3=ffd99c
bright4=b394cf
bright5=e07898
bright6=6abdbd
bright7=fdf6e3
