$activeBorderColor = rgb(87c700)

general {
    col.active_border = $activeBorderColor
}

decoration {
    rounding = 14
    rounding_power = 4
}

group {
    col.border_active = $activeBorderColor
}
